### ISSUE TITLE
Cannot build with G++ 6.2.0

### ISSUE THREAD

**Issue by Salamandar** [ovilab/elegant-hdf5#2]
I tried to build on MingW, with g++ 6.2.0. There seems to be a problem with some lambda-functions : 

```
group.cpp: In member function 'std::vector<std::__cxx11::basic_string<char> > elegant::hdf5::Group::keys() const':
group.cpp:89:21: error: cannot convert 'elegant::hdf5::Group::keys() const::<lambda(hid_t, const char*, const H5L_info_t*, void*)>' to 'H5L_iterate_t {aka int (*)(int, const char*, const H5L_info_t*, void*)}' for argument '5' to 'herr_t H5Literate(hid_t, H5_index_t, H5_iter_order_t, hsize_t*, H5L_iterate_t, void*)'
     }, &returnedKeys);
                     ^
```
I just don't understand why this compiler doesn't accept the "cast" where gcc-4.9 on my raspbian works fine !
I'll try tomorrow gcc-6.2 on ArchLinux, to see if it's the compiler version or MingW.
